### ISSUE TITLE
Epic :: Responsive Design

### ISSUE THREAD

**Issue by w0rd-driven** [w0rd-driven/beatseek#17]
This is heavily geared towards desktop but I need to be mobile first. Apple Music on mobile is pretty slick too.

There's a Library page instead of a menu but it's fine to take Livebeats approach. I'd rather use that tbh, it's slightly better.

- [ ] Mobile sidebar header has too much top padding.
- [ ] Fix sidebar, see #7. The blanket w-1/3 is what's tripping this up I believe. It needs to be full width and 1/3 on desktop.
- [ ] Artist :: Show and Album :: Index are 2 columns with artwork, name, and year only. Non sidebar LiveView likely needs to be full on mobile and 2/3 on desktop or whatever ratio I settle on.
- [ ] Back button on sticky header with label.
- [ ] Opaque sticky header on Artist :: Index, Artist :: Show, Album :: Index, Album :: Show. Album show page has three dot menu and no sort. It also lists songs, which we don't do.
- [ ] Opaque sticky footer
- [ ] Verify page layouts between desktop and mobile. Album :: Show is off. Artist :: Index table from Phoenix sucks a huge dick or I just have the classes all wrong. It scrolls to the right when I don't want that. I should build unique components for that page.
- [ ] Find when you pull down on Artist :: Index, Artist :: Show, Albums :: Index
- [ ] Text transitions from page to sticky header when you scroll down (flick up). Show/Hide on view, scroll thresholds. Likely uses infinite scroll observer technique in the other direction. I'm sure this exists with a Google search.
- [ ] Sort on Artist :: Show, Albums :: Index, Notifications :: Index. Where does verify menu come in? Make the sidebar page aware? It already is. Sort by title, recently added (file modified date?) and entity name (artist, album) don't use a generic term like name even if that's the field in both.
- [ ] Scroll position remembered on back button.
- [ ] Dark/Light mode
- [ ] A-Z # scrolling control. No clue how this would work for infinite scroll tbh. I don't think it would.

I may never implement all of this but if I can get the header, footer, and text transitions to complete the header behavior then the rest could be left. There's a lot here. I need to focus on other ideas and get this to good enough(TM) and not perfect.

These tasks also need to be split into separate issues and attached to the public milestone.

![image](https://user-images.githubusercontent.com/489986/213897704-2bfbe976-0a4b-41d2-b947-3d072130622f.png)

![image](https://user-images.githubusercontent.com/489986/213897740-920fbba7-f209-4768-8378-289f466ca1e9.png)

![image](https://user-images.githubusercontent.com/489986/213897742-32c34b77-8733-4bb1-b152-c4b37c4c4c0a.png)

![image](https://user-images.githubusercontent.com/489986/213897747-506e28eb-2733-4a87-8136-6c7a39958443.png)

![image](https://user-images.githubusercontent.com/489986/213897752-b6cb88f2-c7f8-4839-8f6f-fd8892e7ab27.png)

![image](https://user-images.githubusercontent.com/489986/213897760-8147ddac-6606-4efd-9bfa-2149ddb2a701.png)

![image](https://user-images.githubusercontent.com/489986/213897771-fa14d406-b350-4ec3-93d1-026e514d1b52.png)

![image](https://user-images.githubusercontent.com/489986/213897781-7dcdf2d7-93eb-43e6-b108-30143ae6ba8a.png)

![image](https://user-images.githubusercontent.com/489986/213897785-24b5be41-e0e9-4b82-9b5a-81aec7f8bda0.png)

![image](https://user-images.githubusercontent.com/489986/213897790-7acc9f96-83c0-465f-9669-6667a3fc1019.png)

![image](https://user-images.githubusercontent.com/489986/213897797-bd414c2c-68ad-4aa7-bc3f-c126e708802d.png)

![image](https://user-images.githubusercontent.com/489986/213897805-a9d87e63-c9a0-43d1-a1ae-8383c70bcf81.png)

![image](https://user-images.githubusercontent.com/489986/213897814-132f551a-9ad4-4ca0-8cde-cdc72b3612b9.png)

![image](https://user-images.githubusercontent.com/489986/213897821-19fee8a6-8275-4223-932c-7d17de137437.png)
