### ISSUE TITLE
Epic :: Fix and Add Tests

### ISSUE THREAD

**Issue by w0rd-driven** [w0rd-driven/beatseek#19]
- [x] Rip out create and edit tests. We'll add them back when we add functionality back in.
- [x] Rip out create/edit behavior entirely. We can always reintroduce this but I don't know what it would look like with Apple Music look and feel.
- [x] Nightly integration tests
- [ ] Mock Spotify calls using SpotifyEx examples
- [x] Notification delivery: Type detection, record creation, PubSub
- [x] Scan: detects files, transforms, creates records.
- [x] Verification: ?
- [x] Transformers
- [ ] Oban Workers
