### ISSUE TITLE
Epic :: Bug Squash

### ISSUE THREAD

**Issue by w0rd-driven** [w0rd-driven/beatseek#20]
- [x] Year is used for UI. Need to parse release_date into year as well as day since Abigail Williams has a year-month-day year.
- [x] Genre shows as (9) or is translated from a prior list. Either include that in the transform or use Spotify to update this as well.
- [x] Spotify artist verification may include an image url to use. Worth using if it does.
- [x] Sidebar width in mobile or smaller screens in general. This will be addressed in the mobile sidebar. This is because w-1/3 on mobile looks exactly like it's displaying. Reverse engineering a Tailwind UI component that has a slide out effect will be a better choice.
- [x] Artist :: Index should not use table component. This will be addressed in the component epic. It's a bug on mobile because it has a very awkward width.
- [x] Artist :: Show 2 column layout needs fixed artwork sizes. It should always be a square. This always stretches to a rectangle on a few screens.
- [x] Add validation like unique rules or inclusion to make sure the notification type is one of the enums. The backend process does not have a list, it blindly chooses but got it wrong when I added the album_ prefix.
    - [x] Test if some of this is necessary. Ecto.Enum is supposed to do it for you according to ElixirForum.
