### ISSUE TITLE
Epic :: Demo Mode

### ISSUE THREAD

**Issue by w0rd-driven** [w0rd-driven/beatseek#21]
This is a nice to have that would be worth turning into a library at some point.

- [ ] Create single demo@example.com user or similar with credentials.
- [ ] Break registration or set it behind an environment variable flag to allow people through.
- [ ] Tie content to user id? This seems like a huge lift. We can fudge it for now.
- [ ] Simulate scanning. This would always come from my computer.
