### ISSUE TITLE
Epic :: Settings

### ISSUE THREAD

**Issue by w0rd-driven** [w0rd-driven/beatseek#23]
- [ ] Directories - An embedded schema or 1:M of id, path, and scanned_at.
- [ ] Verified - Last verification timestamp for all artists. A full check should always clear the Artist timestamp. It's fine if we don't persist as we'd always overwrite it anyway.
- [ ] Schedules - This may be fine as we could use different jobs for different schedules. A daily, weekly cron schedule is a diff job than a backfill that schedules the next interval.
- [ ] We could allow users to specify music API but this is a big lift and requires multiple credentials. This would be more for an admin to change site wide.

I don't know how I'll remember this but I'd want to use ElixirKit to create a Livebook app. I don't know what a SaaS or user auth really buys me beyond a demo experience. Users could be tied to Spotify accounts but the library ties my one user. A login flow actually makes zero sense but it was trivial to add. Settings wouldn't be gated behind a login which is why I bring this up.
