### ISSUE TITLE
Public Milestone

### ISSUE THREAD

**Issue by w0rd-driven** [w0rd-driven/beatseek#24]
This issue is to talk through the bare minimum. My brain wants every epic and issue closed but that's not realistic. I can't create milestones on the mobile app. I'll close if there's overlap and I could put all this there.

- [x] Add license file
- [x] Bug squash - Some of these are low hanging fruit. The UI should look the same between owned and not owned.
- [x] Notification icons - Choosing a different icon for not owned that isn't the red x, what we use to close notifications. Then we can unify not owned with the others standing out.
- [x] Fix and add tests
- [x] Scan directory shouldn't be configured in a function default. This can be a compile time config variable set via environment variables just like Spotify.
- [x] Add badges for Artist and Album. PubSub can be configured later.
- [ ] Mobile sidebar. If responsive is good enough this becomes less of a necessity. It isn't sticky on mobile like I expect though it is on desktop.
- [ ] Responsive design - I want it mobile friendly. It's ugly as hell and some of this are quick tweaks.
- [ ] Components - This isn't much of a refactor but it isn't a quick fix. This would "fix" the Artist :: Index table.
- [ ] Oban via the UI. We can instruct people on what to push. Backend processes should set timestamps to nil and trigger jobs. We should be able to test these functions easier than UI. The scanner and verification can be a place for these even if it seems like a smell. Having independent modules for 1 function each seems overkill and we can always refactor.

Nice to haves
- [ ] Landing page - this feels necessary but having dancing icons will be difficult. It may not be too difficult to just have a call to action that goes to the Artist page though. I'm fine with just the readme for now.
- [ ] Pagination would be nice but this is a significant change that would benefit from tests first.
- [ ] Find and sort on all pages. Notifications will need it desperately. They should be simple enough to implement but again, tests will help.
